name: runtracker
description: A sample web application
dependencies:
  async_await:
    git: https://github.com/dart-lang/async_await.git
  browser: any
  core_elements: '>=0.3.2 <0.5.0'
  intl: '>=0.12.0+1 <0.13.0'
  paper_elements: '>=0.5.0 <0.6.0'
  polymer: '>=0.14.0 <0.16.0'
transformers:
- polymer:
    entry_points: web/runtracker.html
- async_await
