name: RunTracker
description: A sample web application
dependencies:
  browser: any
  polymer: ">=0.15.1 <0.16.0"
  core_elements: ">=0.4.0 <0.5.0"
  paper_elements: ">=0.5.0 <0.6.0"
  intl: ">=0.11.11 <0.12.0"
transformers:
- polymer:
    entry_points: web/runtracker.html
